### ISSUE TITLE
Incorrect 'CAA record is not "letsencrypt.org"'

### ISSUE THREAD

**Issue by djbe** [willnode/forward-domain#12]
Getting this issue for the domain `appwise.be`. Doesn't seem to be related to #11.

The CAA records are there, there are even multiple (one for wildcards, and also one for `iodef` (reporting issues). 

The call to `dns.google/resolve` results in:
```json
{
  "Answer":
  [
    {
      "name": "appwise.be.",
      "type": 257,
      "TTL": 21600,
      "data": "0 issuewild \"letsencrypt.org\""
    },
    {
      "name": "appwise.be.",
      "type": 257,
      "TTL": 21600,
      "data": "0 issue \"letsencrypt.org\""
    },
    {
      "name": "appwise.be.",
      "type": 257,
      "TTL": 21600,
      "data": "0 iodef \"mailto:caapolicy@appwise.be\""
    }
  ]
}
```

I think the code is tripping up because of this, because it assumes there should only be one `257` record with the expected CAA contents. It should instead check in the list of `257` records if any is for `issue`, and if so, it must contain the value `letsencrypt.org`.

The spec for CAA records allows the `flag` field to be something else than `0`, although I've yet to see something besides the value `0`.

----

Potential solution would be changing the [`for` loop here](https://github.com/willnode/forward-domain/blob/main/src/util.js#L124-L132) to something like:
```js
const issueRecord = data.Answer.find( item =>
  item.type == 257 && typeof item.data === 'string' && item.data.startsWith('0 issue ')
);

if (issueRecord.data !== "0 issue \"letsencrypt.org\"") {
  return issueRecord.data;
} else {
  return null;
}
```

That last `if` test could even be a simple `issueRecord.data.includes('letsencrypt.org')`. I think the quotes (`"`) are optional around a CAA `value`.

Note: I don't usually write JS code, so please ignore my formatting if it looks weird 😅

**Comment by djbe** [comment]
Actually, there may be multiple `issue` records (to handle multiple cert issuers). So it should be something like:
```js
const issueRecords = data.Answer.filter(x =>
  x.type == 257 && typeof x.data === 'string' && x.data.startsWith('0 issue ')
).map(x => x.data);

// check if any record allows LetsEncrypt (or no record)
if (issueRecords.length == 0 || issueRecords.some(x => x.includes('letsencrypt.org'))) {
  return null;
} else {
  // 
  return issueRecords;
}
```

**Comment by willnode** [comment]
Synced for `r.forwarddomain.net`. Is it work for you?

**Comment by djbe** [comment]
Seems like I missed something when copy pasting code for the PR, so made a quick fix in #14, sorry! 🙏

**Comment by willnode** [comment]
Synced. Please try again.

**Comment by djbe** [comment]
Ugh, now it's `issueRecords` not defined, because the variable is called `issueRecord` 🤦

**Comment by djbe** [comment]
Want me to create another patch?

**Comment by willnode** [comment]
Np. Let me check thoroughly this time.

**Comment by willnode** [comment]
Anyway you can try run tests locally. It's not that hard. Simply follow setup from CI, and replace any occurences of `r.forwarddomain.net` with yours in `test` folder.

**Comment by willnode** [comment]
I've reverted `r.forwarddomain.net` to before your PRs. take your time.

**Comment by djbe** [comment]
Took a bit to set up in a Docker container, but got it working eventually. 

After fixing the typo, I also had to tweak the tests for the "target" domain and the response code (301 instead of 302). But that's to be expected, the config of that domain is just different.

**Comment by willnode** [comment]
Synced. Thank you!

Btw, can you share your Dockerfile? Many people wanted it but I haven't got time to setup it.

**Comment by djbe** [comment]
Oh uhm I didn't actually Docker-ify it, I grabbed a generic ubuntu image and installed the necessary binaries manually.

I'll take a look tomorrow about actually writing one. Would this be for running the service itself, or running the tests? (or both?)

**Comment by willnode** [comment]
I opened #16 for this. Only for service needed now.
