### ISSUE TITLE
[Request] Status codes 307 and 308 support

### ISSUE THREAD

**Issue by vDeggial** [willnode/forward-domain#20]
I would like to request support for status codes 307 and 308

Thanks

**Comment by willnode** [comment]
Should be implemented as of https://github.com/willnode/forward-domain/commit/4d8ffcae4fc4ebc2ebad94ee11c7e3c40c38b2b9

**Comment by vDeggial** [comment]
> Should be implemented as of [4d8ffca](https://github.com/willnode/forward-domain/commit/4d8ffcae4fc4ebc2ebad94ee11c7e3c40c38b2b9)

Thanks :)
