### ISSUE TITLE
Can't add txt record with underscore in namecheap

### ISSUE THREAD

**Issue by lordvcs** [willnode/forward-domain#22]
I am trying setup the redirect by adding the dns entries generated by https://forwarddomain.net/.
But when trying to add the txt record, when I enter the underscore "_", the input says its not a valid hostname
![image](https://github.com/willnode/forward-domain/assets/6374881/ac9b6531-ff51-4975-bcb9-ef2e880f73d2)
What am I doing wrong?

For an example case of redirecting from https://example.ai/ to https://new.com,
the generated DNS records look like the following,
![image](https://github.com/willnode/forward-domain/assets/6374881/6403ca85-1b54-4d81-91b0-70fdec5ea2d0)
So, from what I understand the value of the host field in the txt record would be "_"[underscore character].
Is my understanding wrong?

**Comment by willnode** [comment]
I haven't check namecheap but try to enter `_.@`.

If it still doesn't work, either try asking for support to add the value or use Cloudflare as your domain NS.

**Comment by lordvcs** [comment]
Ok thanks for the reply.

I am assuming that this is not a feature/bug that needs a PR, so I am closing this issue
