### ISSUE TITLE
Missing CA cert after restart

### ISSUE THREAD

**Issue by DeBuXer** [willnode/forward-domain#26]
First of all, I want to say that this tool looks very useful! However, I was wondering how the CA certs are stored? I am encountering the problem that when I restart the NodeJS application, my redirects no longer work because the certificate chain is incomplete. I have the same issue when I use the Docker container.

This is what I get after restarting the application and fetch the certificate with OpenSSL:

```
openssl s_client -showcerts -servername domain.tld --connect domain.tld:443 </dev/null 
CONNECTED(00000003)
depth=0 CN = domain.tld
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = domain.tld
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 CN = domain.tld
verify return:1
```

**Comment by willnode** [comment]
All ca certs are stored in sqlite database.

[const dbFile = path.join(__dirname, '../.certs/db.sqlite');](https://github.com/willnode/forward-domain/blob/main/src/sni.js#L21)

When restarted, it should resume serving HTTPS with these certificates, so I'm not entirely sure why it happened to you.

**Comment by DeBuXer** [comment]
Thanks for your reply!

These certificates are indeed also served after a restart. However, when I convert the BLOB data from the database to text, I only see the private key and cert (before and after a restart). The CA/intermediate cert is not included, which causes it to fail for me.

**Comment by willnode** [comment]
Oh, sorry. I think I misread the whole topic. Let's start again.

No, we don't intermediate cert. I wasn't though I need to save CA cert until recently.

https://github.com/willnode/forward-domain/blob/cc804729effb7ad28eb1a4432466e937ec3f78a9/src/db.js#L149-L162

The `cert` here contains the certificate and the CA. To save storage I do conversion to DER/binary format, but I only save the `x509.raw` here. The CA file you're looking for is in `x509.ca`, it doesn't get saved here.

**Comment by willnode** [comment]
I'm not entirely understand why a CA is needed I think it definitely breaks "chain of trust". Does it will break some browsers?

**Comment by willnode** [comment]
Yes, current behavior only store CA in memory. This is a bug since I moved the storage to sqlite around three months ago. Luckily I don't restart the service over the time.

I'll refactor current db to store CA.
