### ISSUE TITLE
Allow decide between using 301 or 302 http status in the TXT record

### ISSUE THREAD

**Issue by dzegarra** [willnode/forward-domain#3]
I found that the 301 status is hardcoded in the code. But not everyone wants to mark a domain/subdomain to be permanently moved to another. I think that could be configured in the same TXT record. What do you think?

**Comment by willnode** [comment]
I think that's make sense.

Let's see if I/someone can bring this up.

**Comment by dzegarra** [comment]
I propose this changes: https://github.com/willnode/forward-domain/pull/4

**Comment by willnode** [comment]
Merged and confirmed to work. Thank you.
