### ISSUE TITLE
Service forwarddomain.net is down

### ISSUE THREAD

**Issue by p-tchaikovsky** [willnode/forward-domain#6]
Hello, I would like to thank you for creating such a cool and useful project. I have been using [Forward Domain](https://forwarddomain.net/) for some time and it has been working great. 

However, according to <https://stats.uptimerobot.com/AA77Xt9Jx8>, for the past two days, the service has been down and unavailable.

I just would like to let you know about this issue. Thank you again for your hard work on this project.

P. S.
I thought it would be back up in a day, but I had to resort to using a Cloudflare worker today to set up forwarding.

**Comment by willnode** [comment]
Sorry! A misconfiguration happened and I missed the email. It's up now.

**Comment by p-tchaikovsky** [comment]
Thank you ;-)

**Comment by vDeggial** [comment]
Now I keep getting The record data for domain is missing although I have CNAME and TXT records correctly set

**Comment by willnode** [comment]
@vDeggial do you set the TXT record correctly with `_.` prefix? May I check which domain?

**Comment by vDeggial** [comment]
I did and inventory.jricards.com
