### ISSUE TITLE
Feature request: Whitelisting

### ISSUE THREAD

**Issue by VincentSC** [willnode/forward-domain#8]
Great idea and nice implementation!

Is whitelisting by domains and/or by IPs possible?

**Comment by willnode** [comment]
Good idea about whitelisting by domains! We already have a blacklist implemented.

**Comment by VincentSC** [comment]
Thanks for liking the idea! Do you need something for me to help with that? I'm not able to make a PR myself any time soon, unfortunately. :(

**Comment by willnode** [comment]
Oh right no problem I think I can handle that. I think have some free time this week.

**Comment by willnode** [comment]
Whoops that was fast. I haven't tested it yet but I'm confident it should work.

**Comment by VincentSC** [comment]
*blinks*

That's fast!

I see what you do with: 
```
if (whitelistMap === null) {
    return blacklistMap[getCanonDomain(domain)];
} else {
    return !whitelistMap[getCanonDomain(domain)];
}
```
So then it goes to `blacklistRedirectUrl` when not whitelisted. That should work, but might require the text on that url to take that into consideration - should be obvious.

As I did not want to have an open service, the whitelist was a blocking issue. So many thanks!

TODO: dockerize this and test it.
